version: '3.7'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:     
      - /var/run/docker.sock:/tmp/docker.sock:ro    
  php-web:
    build: 
      context: ./php_web
      dockerfile: Dockerfile
      args:
        PROXY: ${PROXY}        
    volumes:
      - ./webapp:/var/www/html
    environment:
      - VIRTUAL_HOST=${DOMAIN}
    depends_on:      
      - mysqldb
      - redis
    # ports:
    # - "8081:80"
  mysqldb:
      image: mariadb/server:${MYSQL_VERSION}
      restart: always      
      environment:
          - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      ports:
          - "8989:3306"
      volumes:
          - "./mysql/data:/var/lib/mysql"
  redis:
    container_name: ${REDIS_HOST}
    image: redis:alpine     
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data      
